services:
  prometheus:
    build:
      context: .
      dockerfile_inline: |
        FROM prom/prometheus
        COPY prometheus.yml /etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
    ports:
      - 19090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy
        RUN cat <<EOF > /etc/caddy/Caddyfile
        prometheus.${DOMAIN:-monitoring.sikademo.com} {
          reverse_proxy prometheus:9090
        }
        grafana.${DOMAIN:-monitoring.sikademo.com} {
          reverse_proxy grafana:3000
        }
        EOF
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-data:/data
volumes:
  prometheus-data:
  caddy-data:
